name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main  # Deploy only when code is pushed to main (after PR merge)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install


  deploy:
    needs: build  # Run deployment only after build succeeds
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only deploy on push to main
    steps:
      - name: Deploy to Private Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          debug: true
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd  ~/media/raj/OS/PROJECTS/test-ci-cd # Change to your project folder
            git pull origin main  # Pull the latest code
            npm install  # Install new dependencies if needed
            pm2 restart all  # Restart the app with PM2
